import { useEffect, useMemo, useState } from 'react';
import { Building2, CalendarDays, ChevronRight, CircleDollarSign, FileText, FolderKanban, Mail, MapPin, NotebookPen, Phone, Plus, Search, Tag, UserRound, X } from 'lucide-react';
import type { Customer, Estimate, Invoice, Project } from '../types';
import { getStored, setStored, uid } from '../lib/storage';

const currency=(value:number)=>new Intl.NumberFormat('en-GH',{style:'currency',currency:'GHS'}).format(value||0);
const emptyCustomer:Omit<Customer,'id'>={name:'',phone:'',email:'',address:'',company:'',contactPerson:'',siteAddress:'',billingAddress:'',gpsLocation:'',siteType:'Residential',status:'Active',tags:[],notes:'',preferredInstallDate:'',networkAvailability:'Unknown',existingEquipment:'',warrantyExpiry:'',maintenanceInterval:'',createdAt:'',updatedAt:''};

export default function CustomerCRM(){
 const[active,setActive]=useState(location.hash.includes('/customers'));
 const[customers,setCustomers]=useState<Customer[]>(()=>getStored('q-customers',[]));
 const[query,setQuery]=useState('');
 const[selected,setSelected]=useState<Customer|null>(null);
 const[formOpen,setFormOpen]=useState(false);
 const[editing,setEditing]=useState<Customer|null>(null);
 const[form,setForm]=useState<any>(emptyCustomer);
 const estimates=getStored<Estimate[]>('q-estimates',[]),invoices=getStored<Invoice[]>('q-invoices',[]),projects=getStored<Project[]>('q-projects',[]);
 useEffect(()=>{const sync=()=>setActive(location.hash.includes('/customers'));addEventListener('hashchange',sync);return()=>removeEventListener('hashchange',sync)},[]);
 useEffect(()=>{if(!active)return;const old=document.body.classList.contains('crm-active');document.body.classList.add('crm-active');return()=>{if(!old)document.body.classList.remove('crm-active')}},[active]);
 const saveAll=(next:Customer[])=>{setCustomers(next);setStored('q-customers',next)};
 const filtered=useMemo(()=>customers.filter(c=>[c.name,c.company,c.phone,c.email,c.address,c.siteAddress,(c.tags||[]).join(' ')].join(' ').toLowerCase().includes(query.toLowerCase())),[customers,query]);
 const totals=(c:Customer)=>{const ci=invoices.filter(i=>i.customerId===c.id||i.customer===c.name),ce=estimates.filter(e=>e.customerId===c.id||e.customer===c.name),cp=projects.filter(p=>p.customerId===c.id||p.customer===c.name);return{billed:ci.reduce((s,i)=>s+i.amount,0),paid:ci.reduce((s,i)=>s+i.paid,0),outstanding:ci.reduce((s,i)=>s+Math.max(0,i.amount-i.paid),0),invoices:ci.length,estimates:ce.length,projects:cp.length,activeProjects:cp.filter(p=>p.status!=='Completed').length,history:[...ci.map(i=>({date:i.date,title:`Invoice ${i.id}`,detail:`${i.status} · ${currency(i.amount)}`,icon:'invoice'})),...ce.map(e=>({date:e.date,title:`Estimate ${e.id}`,detail:`${e.status} · ${currency(e.amount)}`,icon:'estimate'})),...cp.map(p=>({date:p.startDate,title:p.name,detail:`Project · ${p.status}`,icon:'project'}))].sort((a,b)=>String(b.date).localeCompare(String(a.date)))}};
 const openNew=()=>{setEditing(null);setForm({...emptyCustomer,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});setFormOpen(true)};
 const openEdit=(c:Customer)=>{setEditing(c);setForm({...emptyCustomer,...c,tags:c.tags||[]});setFormOpen(true)};
 const submit=()=>{if(!form.name.trim()||!form.phone.trim())return;const customer:Customer={...form,id:editing?.id||uid('CUS'),tags:Array.isArray(form.tags)?form.tags:String(form.tags||'').split(',').map((x:string)=>x.trim()).filter(Boolean),address:form.address||form.siteAddress||'',updatedAt:new Date().toISOString(),createdAt:editing?.createdAt||new Date().toISOString()};const next=editing?customers.map(c=>c.id===editing.id?customer:c):[customer,...customers];saveAll(next);setFormOpen(false);setEditing(null);setSelected(customer)};
 if(!active)return null;
 return <div className="crmMount"><section className="crmPage">
  <header className="crmHero"><div><span>CUSTOMER RELATIONSHIPS</span><h1>Customers & CRM</h1><p>Keep customer contacts, site information, balances and job history connected.</p></div><button className="primary" onClick={openNew}><Plus size={17}/>Add customer</button></header>
  <div className="crmStats"><Metric label="Customers" value={String(customers.length)} icon={<UserRound/>}/><Metric label="Active customers" value={String(customers.filter(c=>(c.status||'Active')==='Active').length)} icon={<Building2/>}/><Metric label="Outstanding" value={currency(customers.reduce((s,c)=>s+totals(c).outstanding,0))} icon={<CircleDollarSign/>}/><Metric label="Active projects" value={String(projects.filter(p=>p.status!=='Completed').length)} icon={<FolderKanban/>}/></div>
  <div className="crmToolbar"><div className="crmSearch"><Search size={18}/><input placeholder="Search name, phone, company, tag or address…" value={query} onChange={e=>setQuery(e.target.value)}/></div><span>{filtered.length} customer{filtered.length===1?'':'s'}</span></div>
  <div className="crmGrid">{filtered.map(c=>{const t=totals(c);return <button className="crmCustomerCard" key={c.id} onClick={()=>setSelected(c)}><div className="crmAvatar">{c.name.slice(0,2).toUpperCase()}</div><div className="crmCustomerMain"><div><h3>{c.name}</h3><p>{c.company||c.siteType||'Customer'} · {c.phone}</p></div><div className="crmTags">{(c.tags||[]).slice(0,3).map(tag=><span key={tag}>{tag}</span>)}</div><div className="crmCustomerMeta"><span>{t.activeProjects} active job{t.activeProjects===1?'':'s'}</span><strong className={t.outstanding?'due':''}>{currency(t.outstanding)}</strong></div></div><ChevronRight/></button>})}{filtered.length===0&&<div className="crmEmpty"><UserRound/><h3>No customers found</h3><p>Add a customer or change the search terms.</p><button className="primary" onClick={openNew}><Plus/>Add customer</button></div>}</div>
 </section>
 {selected&&<CustomerDrawer customer={selected} totals={totals(selected)} close={()=>setSelected(null)} edit={()=>openEdit(selected)}/>} 
 {formOpen&&<CustomerForm form={form} setForm={setForm} close={()=>setFormOpen(false)} save={submit} editing={!!editing}/>} 
 </div>
}
function Metric({label,value,icon}:{label:string;value:string;icon:any}){return <article className="crmMetric"><i>{icon}</i><div><span>{label}</span><strong>{value}</strong></div></article>}
function CustomerDrawer({customer,totals,close,edit}:{customer:Customer;totals:any;close:()=>void;edit:()=>void}){return <div className="crmOverlay" onMouseDown={e=>e.target===e.currentTarget&&close()}><aside className="crmDrawer"><div className="drawerHead"><button onClick={close}><X/></button><button className="primary" onClick={edit}>Edit customer</button></div><div className="profileHead"><div className="profileAvatar">{customer.name.slice(0,2).toUpperCase()}</div><div><span>{customer.status||'Active'}</span><h2>{customer.name}</h2><p>{customer.company||customer.siteType||'Customer'}</p></div></div><div className="profileStats"><div><span>Lifetime billed</span><strong>{currency(totals.billed)}</strong></div><div><span>Outstanding</span><strong>{currency(totals.outstanding)}</strong></div><div><span>Projects</span><strong>{totals.projects}</strong></div></div><section className="profileSection"><h3>Contact & site</h3><Info icon={<Phone/>} text={customer.phone}/><Info icon={<Mail/>} text={customer.email||'No email added'}/><Info icon={<MapPin/>} text={customer.siteAddress||customer.address||'No site address'}/><Info icon={<Building2/>} text={[customer.siteType,customer.networkAvailability&&`Network: ${customer.networkAvailability}`].filter(Boolean).join(' · ')}/></section><section className="profileSection"><h3>Tags</h3><div className="crmTags large">{(customer.tags||[]).length?(customer.tags||[]).map(t=><span key={t}><Tag size={12}/>{t}</span>):<p>No tags added.</p>}</div></section><section className="profileSection"><h3>Site notes</h3><p>{customer.notes||customer.existingEquipment||'No customer notes yet.'}</p></section><section className="profileSection"><h3>Recent activity</h3>{totals.history.slice(0,8).map((x:any,i:number)=><div className="timelineItem" key={`${x.title}-${i}`}><i>{x.icon==='project'?<FolderKanban/>:x.icon==='invoice'?<CircleDollarSign/>:<FileText/>}</i><div><b>{x.title}</b><span>{x.detail}</span><small>{x.date||'No date'}</small></div></div>)}{!totals.history.length&&<p>No activity recorded yet.</p>}</section></aside></div>}
function Info({icon,text}:{icon:any;text:string}){return <div className="profileInfo"><i>{icon}</i><span>{text}</span></div>}
function CustomerForm({form,setForm,close,save,editing}:{form:any;setForm:(v:any)=>void;close:()=>void;save:()=>void;editing:boolean}){const field=(key:string,label:string,type='text')=><label>{label}<input type={type} value={form[key]||''} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>;return <div className="crmOverlay"><div className="crmModal"><div className="modalHead"><div><span>CUSTOMER RECORD</span><h2>{editing?'Edit customer':'Add a customer'}</h2></div><button onClick={close}><X/></button></div><div className="crmFormGrid">{field('name','Customer or business name')}{field('company','Company (optional)')}{field('contactPerson','Contact person')}{field('phone','Phone number','tel')}{field('email','Email','email')}{field('siteAddress','Site address')}{field('billingAddress','Billing address')}{field('gpsLocation','GPS location or map link')}<label>Site type<select value={form.siteType||'Residential'} onChange={e=>setForm({...form,siteType:e.target.value})}>{['Residential','Office','Shop','Warehouse','School','Hospital','Government','Other'].map(x=><option key={x}>{x}</option>)}</select></label><label>Status<select value={form.status||'Active'} onChange={e=>setForm({...form,status:e.target.value})}><option>Active</option><option>Inactive</option></select></label><label>Network availability<select value={form.networkAvailability||'Unknown'} onChange={e=>setForm({...form,networkAvailability:e.target.value})}>{['Available','Unavailable','Unstable','Unknown'].map(x=><option key={x}>{x}</option>)}</select></label>{field('preferredInstallDate','Preferred installation date','date')}{field('warrantyExpiry','Warranty expiry','date')}{field('maintenanceInterval','Maintenance interval')}{field('tags','Tags (comma separated)')}{field('existingEquipment','Existing equipment')}</div><label className="fullField">Customer and site notes<textarea rows={4} value={form.notes||''} onChange={e=>setForm({...form,notes:e.target.value})}/></label><div className="modalActions"><button onClick={close}>Cancel</button><button className="primary" onClick={save}>{editing?'Save changes':'Create customer'}</button></div></div></div>}
