import { useMemo, useState } from 'react';
import { AlertTriangle, ArrowDownToLine, ArrowLeft, ArrowUpFromLine, Boxes, Building2, History, LayoutDashboard, Package, Plus, Search, Settings2, Sparkles, Truck, X } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import type { Business, InventoryItem, StockMovement, Supplier } from '../types';
import { getStored, setStored, uid } from '../lib/storage';

type View='items'|'suppliers'|'movements';
type TradeLibrary='Electrical'|'CCTV & Security'|'Solar'|'Starlink & Networking'|'Plumbing';
const today=()=>new Date().toISOString().slice(0,10);
const money=(value:number,currency='GHS')=>new Intl.NumberFormat('en-GH',{style:'currency',currency}).format(value||0);
const business=()=>getStored<Business>('q-business',{name:'Quotiq',email:'',phone:'',address:'',taxId:'',bank:'',accountName:'',accountNumber:'',mobileMoney:'',estimatePrefix:'EST',invoicePrefix:'INV',currency:'GHS'});
const libraries:Record<TradeLibrary,Array<Pick<InventoryItem,'name'|'category'|'unit'|'reorderLevel'>>>={
 Electrical:[{name:'1.5 mm² copper cable',category:'Cable',unit:'coils',reorderLevel:2},{name:'2.5 mm² copper cable',category:'Cable',unit:'coils',reorderLevel:2},{name:'20 mm PVC conduit',category:'Conduit',unit:'lengths',reorderLevel:10},{name:'13A double socket',category:'Accessories',unit:'pcs',reorderLevel:10},{name:'LED light fitting',category:'Lighting',unit:'pcs',reorderLevel:8},{name:'Consumer unit / DB',category:'Protection',unit:'sets',reorderLevel:2}],
 'CCTV & Security':[{name:'2MP CCTV camera',category:'Cameras',unit:'pcs',reorderLevel:4},{name:'8-channel DVR / NVR',category:'Recorders',unit:'pcs',reorderLevel:2},{name:'Surveillance hard drive',category:'Storage',unit:'pcs',reorderLevel:2},{name:'Cat6 cable',category:'Cable',unit:'boxes',reorderLevel:2},{name:'RJ45 / BNC connectors',category:'Accessories',unit:'packs',reorderLevel:3},{name:'UPS backup',category:'Power',unit:'pcs',reorderLevel:2}],
 Solar:[{name:'Solar panel',category:'Panels',unit:'pcs',reorderLevel:4},{name:'Hybrid inverter',category:'Inverters',unit:'pcs',reorderLevel:1},{name:'Lithium battery',category:'Batteries',unit:'pcs',reorderLevel:1},{name:'PV cable',category:'Cable',unit:'rolls',reorderLevel:2},{name:'MC4 connector pair',category:'Accessories',unit:'pairs',reorderLevel:10},{name:'DC protection box',category:'Protection',unit:'sets',reorderLevel:2}],
 'Starlink & Networking':[{name:'Starlink kit',category:'Internet equipment',unit:'sets',reorderLevel:1},{name:'Roof / wall mount',category:'Mounting',unit:'sets',reorderLevel:3},{name:'Wi-Fi 6 router',category:'Networking',unit:'pcs',reorderLevel:2},{name:'Outdoor Cat6 cable',category:'Cable',unit:'m',reorderLevel:100},{name:'RJ45 connectors',category:'Accessories',unit:'packs',reorderLevel:3},{name:'Network surge protector',category:'Protection',unit:'pcs',reorderLevel:3}],
 Plumbing:[{name:'PPR / PVC pipe',category:'Pipes',unit:'lengths',reorderLevel:10},{name:'Pipe fittings',category:'Fittings',unit:'pcs',reorderLevel:20},{name:'Stop valve',category:'Valves',unit:'pcs',reorderLevel:5},{name:'Wash hand basin set',category:'Fixtures',unit:'sets',reorderLevel:1},{name:'Water closet set',category:'Fixtures',unit:'sets',reorderLevel:1},{name:'Sealants and consumables',category:'Consumables',unit:'lots',reorderLevel:2}]
};

export default function InventoryV2(){
 const navigate=useNavigate(),biz=business();
 const[view,setView]=useState<View>('items'),[items,setItems]=useState<InventoryItem[]>(()=>getStored('q-inventory',[])),[suppliers,setSuppliers]=useState<Supplier[]>(()=>getStored('q-suppliers',[])),[movements,setMovements]=useState<StockMovement[]>(()=>getStored('q-stock-movements',[])),[query,setQuery]=useState(''),[itemOpen,setItemOpen]=useState(false),[supplierOpen,setSupplierOpen]=useState(false),[moveItem,setMoveItem]=useState<InventoryItem|null>(null),[libraryOpen,setLibraryOpen]=useState(false);
 const saveItems=(next:InventoryItem[])=>{setItems(next);setStored('q-inventory',next)},saveSuppliers=(next:Supplier[])=>{setSuppliers(next);setStored('q-suppliers',next)},saveMovements=(next:StockMovement[])=>{setMovements(next);setStored('q-stock-movements',next)};
 const filtered=useMemo(()=>items.filter(i=>[i.name,i.sku,i.category,i.trade,i.itemType].join(' ').toLowerCase().includes(query.toLowerCase())),[items,query]);
 const stockItems=items.filter(i=>(i.itemType||'Material')==='Material'),low=stockItems.filter(i=>i.quantity<=i.reorderLevel),value=stockItems.reduce((s,i)=>s+i.quantity*i.cost,0),retail=stockItems.reduce((s,i)=>s+i.quantity*i.sellPrice,0);
 return <main className="invPage"><header className="invHero"><div><button className="invBack" onClick={()=>navigate('/')}><ArrowLeft/><LayoutDashboard/>Dashboard</button><span>STOCK & PURCHASING</span><h1>Inventory</h1><p>Control materials, services, suppliers and every stock movement.</p></div><div className="invHeroActions"><button onClick={()=>setLibraryOpen(true)}><Sparkles/>Starter library</button><button className="invPrimary" onClick={()=>setItemOpen(true)}><Plus/>Add item</button></div></header>
 <section className="invStats"><article><i><Boxes/></i><div><span>Items & services</span><strong>{items.length}</strong></div></article><article><i><AlertTriangle/></i><div><span>Low stock</span><strong>{low.length}</strong></div></article><article><i><Package/></i><div><span>Stock cost value</span><strong>{money(value,biz.currency)}</strong></div></article><article><i><Truck/></i><div><span>Potential sales value</span><strong>{money(retail,biz.currency)}</strong></div></article></section>
 <nav className="invTabs"><button className={view==='items'?'active':''} onClick={()=>setView('items')}><Package/>Items</button><button className={view==='suppliers'?'active':''} onClick={()=>setView('suppliers')}><Building2/>Suppliers</button><button className={view==='movements'?'active':''} onClick={()=>setView('movements')}><History/>Stock history</button></nav>
 {view==='items'&&<><div className="invToolbar"><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search item, SKU, category or trade"/></label><span>{filtered.length} records</span></div><section className="invItems">{filtered.length?filtered.map(item=>{const supplier=suppliers.find(s=>s.id===item.supplierId),isLow=(item.itemType||'Material')==='Material'&&item.quantity<=item.reorderLevel;return <article key={item.id}><div className="invItemIcon">{item.itemType==='Service'?<Settings2/>:<Package/>}</div><div className="invItemMain"><div><span>{item.sku||'NO SKU'}</span><h3>{item.name}</h3><p>{item.category}{item.trade?` · ${item.trade}`:''}</p></div>{isLow&&<em><AlertTriangle/>Low stock</em>}</div><div className="invQty"><span>Available</span><strong>{item.itemType==='Service'?'Service':`${item.quantity} ${item.unit}`}</strong><small>Reorder at {item.reorderLevel}</small></div><div className="invPrice"><span>Cost / Sell</span><b>{money(item.cost,biz.currency)}</b><strong>{money(item.sellPrice,biz.currency)}</strong></div><div className="invSupplier"><span>Supplier</span><b>{supplier?.name||'Not assigned'}</b></div>{item.itemType!=='Service'&&<button onClick={()=>setMoveItem(item)}><ArrowDownToLine/>Adjust stock</button>}</article>}):<div className="invEmpty"><Package/><h2>No inventory records</h2><p>Add an item or load a professional trade starter library.</p><button className="invPrimary" onClick={()=>setLibraryOpen(true)}><Sparkles/>Load starter library</button></div>}</section></>}
 {view==='suppliers'&&<section className="invSuppliers"><header><div><h2>Suppliers</h2><p>Keep purchasing contacts connected to inventory items.</p></div><button className="invPrimary" onClick={()=>setSupplierOpen(true)}><Plus/>Add supplier</button></header>{suppliers.length?<div>{suppliers.map(s=><article key={s.id}><i><Building2/></i><div><h3>{s.name}</h3><p>{s.contactPerson||'Supplier'} · {s.phone}</p><span>{s.email||s.address||'No additional contact details'}</span></div><strong>{items.filter(i=>i.supplierId===s.id).length} item{items.filter(i=>i.supplierId===s.id).length===1?'':'s'}</strong></article>)}</div>:<div className="invEmpty"><Building2/><h2>No suppliers yet</h2><p>Add suppliers and connect them to materials you purchase regularly.</p><button className="invPrimary" onClick={()=>setSupplierOpen(true)}><Plus/>Add supplier</button></div>}</section>}
 {view==='movements'&&<section className="invMovements"><header><h2>Stock movement history</h2><p>A traceable record of stock received, used and corrected.</p></header>{movements.length?<div>{movements.map(m=><article key={m.id}><i className={m.type==='Stock In'?'in':m.type==='Stock Out'?'out':''}>{m.type==='Stock In'?<ArrowDownToLine/>:m.type==='Stock Out'?<ArrowUpFromLine/>:<Settings2/>}</i><div><h3>{m.itemName}</h3><p>{m.type} · {m.note||'No note'}</p></div><strong>{m.type==='Stock Out'?'-':'+'}{m.quantity}</strong><span>{m.date}</span></article>)}</div>:<div className="invEmpty"><History/><h2>No stock movements</h2><p>Stock adjustments will create a traceable history here.</p></div>}</section>}
 {itemOpen&&<ItemModal suppliers={suppliers} close={()=>setItemOpen(false)} save={item=>{saveItems([item,...items]);setItemOpen(false)}}/>}{supplierOpen&&<SupplierModal close={()=>setSupplierOpen(false)} save={supplier=>{saveSuppliers([supplier,...suppliers]);setSupplierOpen(false)}}/>}{moveItem&&<MovementModal item={moveItem} suppliers={suppliers} close={()=>setMoveItem(null)} save={(movement,newQty)=>{saveItems(items.map(i=>i.id===moveItem.id?{...i,quantity:newQty}:i));saveMovements([movement,...movements]);setMoveItem(null)}}/>}{libraryOpen&&<LibraryModal close={()=>setLibraryOpen(false)} load={(trade,rows)=>{const existingNames=new Set(items.map(i=>i.name.toLowerCase()));const additions=rows.filter(r=>!existingNames.has(r.name.toLowerCase())).map((r,index):InventoryItem=>({...r,id:uid('STK'),sku:`${trade.slice(0,3).toUpperCase()}-${String(items.length+index+1).padStart(3,'0')}`,quantity:0,cost:0,sellPrice:0,itemType:'Material',trade}));saveItems([...additions,...items]);setLibraryOpen(false);setView('items')}}/>}</main>;
}

function ItemModal({suppliers,close,save}:{suppliers:Supplier[];close:()=>void;save:(item:InventoryItem)=>void}){const[f,setF]=useState({name:'',sku:'',category:'',itemType:'Material' as 'Material'|'Service',quantity:0,reorderLevel:5,unit:'pcs',cost:0,sellPrice:0,supplierId:'',trade:'',notes:''});const submit=()=>{if(!f.name.trim())return;save({...f,id:uid('STK'),name:f.name.trim()})};return <Modal title="Add inventory item" subtitle="Create a material, product or reusable service." close={close}><div className="invForm"><label>Item name *<input value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></label><label>Item type<select value={f.itemType} onChange={e=>setF({...f,itemType:e.target.value as 'Material'|'Service'})}><option>Material</option><option>Service</option></select></label><label>SKU / code<input value={f.sku} onChange={e=>setF({...f,sku:e.target.value})}/></label><label>Category<input value={f.category} onChange={e=>setF({...f,category:e.target.value})}/></label><label>Quantity<input type="number" min="0" value={f.quantity} onChange={e=>setF({...f,quantity:Number(e.target.value)})}/></label><label>Reorder level<input type="number" min="0" value={f.reorderLevel} onChange={e=>setF({...f,reorderLevel:Number(e.target.value)})}/></label><label>Unit<input value={f.unit} onChange={e=>setF({...f,unit:e.target.value})}/></label><label>Trade<input value={f.trade} onChange={e=>setF({...f,trade:e.target.value})}/></label><label>Unit cost<input type="number" min="0" value={f.cost} onChange={e=>setF({...f,cost:Number(e.target.value)})}/></label><label>Selling price<input type="number" min="0" value={f.sellPrice} onChange={e=>setF({...f,sellPrice:Number(e.target.value)})}/></label><label className="full">Supplier<select value={f.supplierId} onChange={e=>setF({...f,supplierId:e.target.value})}><option value="">Not assigned</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label></div><div className="invModalActions"><button onClick={close}>Cancel</button><button className="invPrimary" onClick={submit}>Save item</button></div></Modal>}
function SupplierModal({close,save}:{close:()=>void;save:(supplier:Supplier)=>void}){const[f,setF]=useState({name:'',contactPerson:'',phone:'',email:'',address:'',categories:'',notes:''});const submit=()=>{if(f.name.trim()&&f.phone.trim())save({...f,id:uid('SUP'),name:f.name.trim(),phone:f.phone.trim()})};return <Modal title="Add supplier" subtitle="Save the contact used for purchasing materials." close={close}><div className="invForm"><label>Supplier name *<input value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></label><label>Contact person<input value={f.contactPerson} onChange={e=>setF({...f,contactPerson:e.target.value})}/></label><label>Phone *<input value={f.phone} onChange={e=>setF({...f,phone:e.target.value})}/></label><label>Email<input type="email" value={f.email} onChange={e=>setF({...f,email:e.target.value})}/></label><label className="full">Address<input value={f.address} onChange={e=>setF({...f,address:e.target.value})}/></label><label className="full">Products / categories<input value={f.categories} onChange={e=>setF({...f,categories:e.target.value})}/></label></div><div className="invModalActions"><button onClick={close}>Cancel</button><button className="invPrimary" onClick={submit}>Save supplier</button></div></Modal>}
function MovementModal({item,suppliers,close,save}:{item:InventoryItem;suppliers:Supplier[];close:()=>void;save:(movement:StockMovement,newQty:number)=>void}){const[type,setType]=useState<StockMovement['type']>('Stock In'),[quantity,setQuantity]=useState(1),[note,setNote]=useState(''),[supplierId,setSupplierId]=useState(item.supplierId||'');const submit=()=>{const qty=Math.max(0,quantity);if(!qty)return;const next=type==='Stock In'?item.quantity+qty:type==='Stock Out'?Math.max(0,item.quantity-qty):qty;save({id:uid('MOV'),itemId:item.id,itemName:item.name,date:today(),type,quantity:qty,note:note.trim(),supplierId},next)};return <Modal title={`Adjust ${item.name}`} subtitle={`Current stock: ${item.quantity} ${item.unit}`} close={close}><div className="invForm"><label>Movement type<select value={type} onChange={e=>setType(e.target.value as StockMovement['type'])}><option>Stock In</option><option>Stock Out</option><option>Adjustment</option></select></label><label>{type==='Adjustment'?'New quantity':'Quantity'}<input type="number" min="0" value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/></label><label className="full">Supplier<select value={supplierId} onChange={e=>setSupplierId(e.target.value)}><option value="">Not assigned</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="full">Reason / note<input value={note} onChange={e=>setNote(e.target.value)} placeholder="Purchase, project usage, correction…"/></label></div><div className="invModalActions"><button onClick={close}>Cancel</button><button className="invPrimary" onClick={submit}>Save movement</button></div></Modal>}
function LibraryModal({close,load}:{close:()=>void;load:(trade:TradeLibrary,rows:typeof libraries[TradeLibrary])=>void}){const[trade,setTrade]=useState<TradeLibrary>('Electrical');return <Modal title="Trade starter library" subtitle="Load realistic stock records without prices, then customize them." close={close}><div className="invLibrary"><label>Choose profession<select value={trade} onChange={e=>setTrade(e.target.value as TradeLibrary)}>{(Object.keys(libraries) as TradeLibrary[]).map(t=><option key={t}>{t}</option>)}</select></label><div>{libraries[trade].map(row=><span key={row.name}><Package/>{row.name}<small>{row.unit} · reorder {row.reorderLevel}</small></span>)}</div></div><div className="invModalActions"><button onClick={close}>Cancel</button><button className="invPrimary" onClick={()=>load(trade,libraries[trade])}><Sparkles/>Load {libraries[trade].length} items</button></div></Modal>}
function Modal({title,subtitle,close,children}:{title:string;subtitle:string;close:()=>void;children:React.ReactNode}){return <div className="invOverlay"><section className="invModal"><header><div><span>INVENTORY WORKSPACE</span><h2>{title}</h2><p>{subtitle}</p></div><button onClick={close}><X/></button></header>{children}</section></div>}
