import { useState } from 'react';
import { ArrowLeft, BarChart3, Boxes, CircleDollarSign, Download, LayoutDashboard, Package, PieChart, ReceiptText, TrendingUp, Users, WalletCards } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import type { Business, Customer, Estimate, Expense, InventoryItem, Invoice, Project } from '../types';
import { getStored } from '../lib/storage';

type Range='30d'|'90d'|'year'|'all';
const money=(value:number,currency='GHS')=>new Intl.NumberFormat('en-GH',{style:'currency',currency,maximumFractionDigits:0}).format(value||0);
const biz=()=>getStored<Business>('q-business',{name:'Quotiq',email:'',phone:'',address:'',taxId:'',bank:'',accountName:'',accountNumber:'',mobileMoney:'',estimatePrefix:'EST',invoicePrefix:'INV',currency:'GHS'});
const inRange=(date:string,start:string)=>!start||!date||date>=start;
const rangeStart=(range:Range)=>{if(range==='all')return'';const d=new Date();if(range==='30d')d.setDate(d.getDate()-30);else if(range==='90d')d.setDate(d.getDate()-90);else d.setMonth(0,1);return d.toISOString().slice(0,10)};
const csvCell=(value:unknown)=>`"${String(value??'').replaceAll('"','""')}"`;

export default function ReportsV2(){
 const navigate=useNavigate(),business=biz(),[range,setRange]=useState<Range>('year'),[tab,setTab]=useState<'overview'|'projects'|'customers'|'inventory'>('overview');
 const invoices=getStored<Invoice[]>('q-invoices',[]),expenses=getStored<Expense[]>('q-expenses',[]),projects=getStored<Project[]>('q-projects',[]),inventory=getStored<InventoryItem[]>('q-inventory',[]),customers=getStored<Customer[]>('q-customers',[]),estimates=getStored<Estimate[]>('q-estimates',[]),start=rangeStart(range);
 const filteredInvoices=invoices.filter(i=>inRange(i.date,start)),filteredExpenses=expenses.filter(e=>inRange(e.date,start));
 const invoiced=filteredInvoices.reduce((s,i)=>s+i.amount,0),collected=filteredInvoices.reduce((s,i)=>s+i.paid,0),expense=filteredExpenses.reduce((s,e)=>s+e.amount,0),outstanding=filteredInvoices.reduce((s,i)=>s+Math.max(0,i.amount-i.paid),0),profit=collected-expense,stockValue=inventory.filter(i=>(i.itemType||'Material')==='Material').reduce((s,i)=>s+i.quantity*i.cost,0),metrics={invoiced,collected,expense,outstanding,profit,stockValue,margin:collected?profit/collected*100:0};
 const expenseCategories=Object.entries(filteredExpenses.reduce<Record<string,number>>((acc,e)=>{acc[e.category]=(acc[e.category]||0)+e.amount;return acc},{})).sort((a,b)=>b[1]-a[1]),maxExpense=Math.max(1,...expenseCategories.map(x=>x[1]));
 const months=Array.from({length:6},(_,index)=>{const date=new Date();date.setMonth(date.getMonth()-(5-index));const key=date.toISOString().slice(0,7),label=date.toLocaleDateString('en-GB',{month:'short'});return{key,label,invoiced:invoices.filter(i=>i.date?.startsWith(key)).reduce((s,i)=>s+i.amount,0),collected:invoices.filter(i=>i.date?.startsWith(key)).reduce((s,i)=>s+i.paid,0),expenses:expenses.filter(e=>e.date?.startsWith(key)).reduce((s,e)=>s+e.amount,0)}});
 const maxMonth=Math.max(1,...months.flatMap(m=>[m.invoiced,m.collected,m.expenses]));
 const projectRows=projects.map(p=>{const projectExpenses=expenses.filter(e=>e.projectId===p.id).reduce((s,e)=>s+e.amount,0),materialCost=(p.materials||[]).reduce((s,m)=>s+m.quantity*m.cost,0),cost=Math.max(p.spent||0,projectExpenses+materialCost);return{...p,cost,profit:p.budget-cost,margin:p.budget?(p.budget-cost)/p.budget*100:0}}).sort((a,b)=>b.profit-a.profit);
 const customerRows=customers.map(c=>{const ci=invoices.filter(i=>i.customerId===c.id||i.customer===c.name),ce=estimates.filter(e=>e.customerId===c.id||e.customer===c.name),cp=projects.filter(p=>p.customerId===c.id||p.customer===c.name);return{...c,billed:ci.reduce((s,i)=>s+i.amount,0),paid:ci.reduce((s,i)=>s+i.paid,0),outstanding:ci.reduce((s,i)=>s+Math.max(0,i.amount-i.paid),0),estimates:ce.length,projects:cp.length}}).sort((a,b)=>b.billed-a.billed);
 const stockRows=inventory.filter(i=>(i.itemType||'Material')==='Material').map(i=>({...i,value:i.quantity*i.cost,retail:i.quantity*i.sellPrice,low:i.quantity<=i.reorderLevel})).sort((a,b)=>b.value-a.value);
 // eslint-disable-next-line prefer-const
 const exportCsv=()=>{let rows:(string|number)[][]=[],name='quotiq-report';if(tab==='overview'){rows=[['Metric','Value'],['Invoiced',metrics.invoiced],['Collected',metrics.collected],['Outstanding',metrics.outstanding],['Expenses',metrics.expense],['Net profit',metrics.profit],['Stock value',metrics.stockValue]]}else if(tab==='projects'){rows=[['Project','Customer','Budget','Cost','Profit','Margin %','Status'],...projectRows.map(p=>[p.name,p.customer,p.budget,p.cost,p.profit,p.margin.toFixed(1),p.status])]}else if(tab==='customers'){rows=[['Customer','Phone','Billed','Paid','Outstanding','Estimates','Projects'],...customerRows.map(c=>[c.name,c.phone,c.billed,c.paid,c.outstanding,c.estimates,c.projects])]}else{rows=[['Item','SKU','Category','Quantity','Unit','Cost value','Sales value','Low stock'],...stockRows.map(i=>[i.name,i.sku,i.category,i.quantity,i.unit,i.value,i.retail,i.low?'Yes':'No'])]}const blob=new Blob([rows.map(row=>row.map(csvCell).join(',')).join('\n')],{type:'text/csv'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`${name}-${tab}-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(url)};
 return <main className="repPage"><header className="repHero"><div><button className="repBack" onClick={()=>navigate('/')}><ArrowLeft/><LayoutDashboard/>Dashboard</button><span>BUSINESS INTELLIGENCE</span><h1>Reports & analytics</h1><p>Understand sales, cash, costs, customers, projects and stock performance.</p></div><div className="repActions"><select value={range} onChange={e=>setRange(e.target.value as Range)}><option value="30d">Last 30 days</option><option value="90d">Last 90 days</option><option value="year">This year</option><option value="all">All time</option></select><button onClick={exportCsv}><Download/>Export CSV</button></div></header>
 <section className="repKpis"><article><i><ReceiptText/></i><div><span>Invoiced</span><strong>{money(metrics.invoiced,business.currency)}</strong><small>{filteredInvoices.length} invoices</small></div></article><article><i><CircleDollarSign/></i><div><span>Collected</span><strong>{money(metrics.collected,business.currency)}</strong><small>{metrics.invoiced?Math.round(metrics.collected/metrics.invoiced*100):0}% collection rate</small></div></article><article><i><WalletCards/></i><div><span>Outstanding</span><strong>{money(metrics.outstanding,business.currency)}</strong><small>{filteredInvoices.filter(i=>i.status!=='Paid').length} open invoices</small></div></article><article><i><TrendingUp/></i><div><span>Net cash profit</span><strong className={metrics.profit<0?'negative':''}>{money(metrics.profit,business.currency)}</strong><small>{metrics.margin.toFixed(1)}% cash margin</small></div></article></section>
 <nav className="repTabs"><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}><BarChart3/>Overview</button><button className={tab==='projects'?'active':''} onClick={()=>setTab('projects')}><TrendingUp/>Projects</button><button className={tab==='customers'?'active':''} onClick={()=>setTab('customers')}><Users/>Customers</button><button className={tab==='inventory'?'active':''} onClick={()=>setTab('inventory')}><Boxes/>Inventory</button></nav>
 {tab==='overview'&&<div className="repOverview"><article className="repCard repTrend"><header><div><span>6-MONTH TREND</span><h2>Sales, collections and expenses</h2></div><div className="repLegend"><i className="quoted"/>Invoiced<i className="paid"/>Collected<i className="cost"/>Expenses</div></header><div className="repChart">{months.map(month=><div key={month.key}><div className="repBars"><i className="quoted" style={{height:`${Math.max(3,month.invoiced/maxMonth*100)}%`}} title={`Invoiced ${money(month.invoiced,business.currency)}`}/><i className="paid" style={{height:`${Math.max(3,month.collected/maxMonth*100)}%`}} title={`Collected ${money(month.collected,business.currency)}`}/><i className="cost" style={{height:`${Math.max(3,month.expenses/maxMonth*100)}%`}} title={`Expenses ${money(month.expenses,business.currency)}`}/></div><span>{month.label}</span></div>)}</div></article><article className="repCard repExpense"><header><span>SPENDING</span><h2>Expense breakdown</h2></header>{expenseCategories.length?expenseCategories.map(([category,value])=><div key={category}><span>{category}</span><i><b style={{width:`${value/maxExpense*100}%`}}/></i><strong>{money(value,business.currency)}</strong></div>):<div className="repNoData">No expenses in this period.</div>}</article><article className="repCard repSummary"><header><span>FINANCIAL POSITION</span><h2>Business summary</h2></header><div><span>Gross invoiced</span><b>{money(metrics.invoiced,business.currency)}</b></div><div><span>Cash collected</span><b>{money(metrics.collected,business.currency)}</b></div><div><span>Operating expenses</span><b>- {money(metrics.expense,business.currency)}</b></div><div className="total"><span>Net cash profit</span><strong>{money(metrics.profit,business.currency)}</strong></div><div><span>Inventory cost value</span><b>{money(metrics.stockValue,business.currency)}</b></div></article><article className="repCard repAttention"><header><span>ATTENTION REQUIRED</span><h2>Business alerts</h2></header><p><WalletCards/><span><b>{money(metrics.outstanding,business.currency)}</b> outstanding from customers</span></p><p><Package/><span><b>{stockRows.filter(i=>i.low).length}</b> inventory items at or below reorder level</span></p><p><CircleDollarSign/><span><b>{filteredInvoices.filter(i=>i.status==='Partially Paid').length}</b> partially paid invoices</span></p></article></div>}
 {tab==='projects'&&<ReportTable title="Project profitability" subtitle="Budget compared with recorded project and material costs." columns={['Project','Customer','Budget','Cost','Profit','Margin','Status']} rows={projectRows.map(p=>[p.name,p.customer,money(p.budget,business.currency),money(p.cost,business.currency),money(p.profit,business.currency),`${p.margin.toFixed(1)}%`,p.status])}/>} 
 {tab==='customers'&&<ReportTable title="Customer performance" subtitle="Lifetime billing, collection and activity by customer." columns={['Customer','Phone','Billed','Paid','Outstanding','Estimates','Projects']} rows={customerRows.map(c=>[c.name,c.phone,money(c.billed,business.currency),money(c.paid,business.currency),money(c.outstanding,business.currency),String(c.estimates),String(c.projects)])}/>} 
 {tab==='inventory'&&<><section className="repInventoryStats"><article><span>Cost valuation</span><strong>{money(stockRows.reduce((s,i)=>s+i.value,0),business.currency)}</strong></article><article><span>Potential sales value</span><strong>{money(stockRows.reduce((s,i)=>s+i.retail,0),business.currency)}</strong></article><article><span>Potential gross margin</span><strong>{money(stockRows.reduce((s,i)=>s+i.retail-i.value,0),business.currency)}</strong></article><article><span>Low stock items</span><strong>{stockRows.filter(i=>i.low).length}</strong></article></section><ReportTable title="Inventory valuation" subtitle="Quantity, cost value, retail value and stock health." columns={['Item','SKU','Category','Available','Cost value','Sales value','Status']} rows={stockRows.map(i=>[i.name,i.sku||'—',i.category,`${i.quantity} ${i.unit}`,money(i.value,business.currency),money(i.retail,business.currency),i.low?'Low stock':'Healthy'])}/></>}
 </main>;
}

function ReportTable({title,subtitle,columns,rows}:{title:string;subtitle:string;columns:string[];rows:string[][]}){return <section className="repTableCard"><header><h2>{title}</h2><p>{subtitle}</p></header>{rows.length?<div><table><thead><tr>{columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={`${row[0]}-${index}`}>{row.map((cell,i)=><td key={`${i}-${cell}`}>{cell}</td>)}</tr>)}</tbody></table></div>:<div className="repNoData"><PieChart/>No records available for this report.</div>}</section>}
