export type Customer={id:string;name:string;phone:string;email:string;address:string;company?:string;contactPerson?:string;siteAddress?:string;billingAddress?:string;gpsLocation?:string;siteType?:string;status?:'Active'|'Inactive';tags?:string[];notes?:string;preferredInstallDate?:string;networkAvailability?:string;existingEquipment?:string;warrantyExpiry?:string;maintenanceInterval?:string;createdAt?:string;updatedAt?:string};
export type LineItem={id:string;description:string;qty:number;unit:string;rate:number};
export type EstimateOption={id:string;name:string;tagline:string;description:string;multiplier:number;warranty:string;recommended?:boolean};
export type Estimate={id:string;customerId:string;customer:string;project:string;amount:number;status:'Draft'|'Pending'|'Accepted';date:string;items:LineItem[];tax:number;discount:number;validDays?:number;reference?:string;trade?:string;notes?:string;terms?:string;paymentDetails?:string;pricingStyle?:'standard'|'choices';options?:EstimateOption[];depositPercent?:number;preferredStart?:string;internalCost?:number;selectedOptionId?:string};
export type PaymentRecord={id:string;date:string;amount:number;method:string;reference?:string};
export type Invoice={id:string;customerId?:string;customer:string;project:string;amount:number;paid:number;status:'Unpaid'|'Partially Paid'|'Paid';date:string;items:LineItem[];tax?:number;discount?:number;dueDate?:string;lastPaymentDate?:string;estimateId?:string;payments?:PaymentRecord[]};
export type DocumentTemplate='modern'|'classic'|'minimal'|'emerald'|'sunset'|'industrial'|'royal';
export type Business={name:string;email:string;phone:string;address:string;taxId:string;bank:string;accountName:string;accountNumber:string;mobileMoney:string;estimatePrefix:string;invoicePrefix:string;currency:string;logo?:string;signature?:string;authorizedName?:string;authorizedTitle?:string;stamp?:string;terms?:string;documentTemplate?:DocumentTemplate};
export type ProjectTask={id:string;title:string;completed:boolean;assignee?:string;dueDate?:string};
export type ProjectMaterial={id:string;inventoryId?:string;name:string;quantity:number;unit:string;cost:number};
export type ProjectPhoto={id:string;name:string;dataUrl:string;caption?:string;date:string};
export type ProjectActivity={id:string;date:string;type:string;message:string};
export type ProjectTimeEntry={id:string;member:string;date:string;hours:number;hourlyRate:number;note?:string;sourceEntryId?:string};
export type ProjectInspectionItem={id:string;label:string;completed:boolean;note?:string};
export type ProjectInspection={id:string;title:string;status:'Open'|'Passed';items:ProjectInspectionItem[];updatedAt:string};
export type ScheduleStatus='Scheduled'|'Dispatched'|'In Progress'|'Completed';
export type Project={id:string;customerId:string;customer:string;name:string;status:'Planned'|'In Progress'|'Completed'|'On Hold';startDate:string;dueDate:string;budget:number;spent:number;assignee:string;notes:string;stage?:string;siteAddress?:string;estimateId?:string;invoiceId?:string;tasks?:ProjectTask[];materials?:ProjectMaterial[];photos?:ProjectPhoto[];activities?:ProjectActivity[];timeEntries?:ProjectTimeEntry[];inspections?:ProjectInspection[];scheduleDate?:string;scheduleStart?:string;scheduleEnd?:string;scheduleStatus?:ScheduleStatus;crewMemberIds?:string[];scheduleNotes?:string};
export type InventoryItem={id:string;name:string;sku:string;category:string;quantity:number;reorderLevel:number;unit:string;cost:number;sellPrice:number;itemType?:'Material'|'Service';supplierId?:string;trade?:string;notes?:string};
export type Supplier={id:string;name:string;contactPerson?:string;phone:string;email?:string;address?:string;categories?:string;notes?:string};
export type StockMovement={id:string;itemId:string;itemName:string;date:string;type:'Stock In'|'Stock Out'|'Adjustment';quantity:number;note:string;supplierId?:string};
export type Expense={id:string;date:string;category:string;description:string;projectId:string;amount:number;paymentMethod:string};
export type PurchaseOrderStatus='Draft'|'Ordered'|'Partially Received'|'Received'|'Cancelled';
export type PurchaseOrderLine={id:string;inventoryId?:string;description:string;sku?:string;qty:number;receivedQty:number;unit:string;unitCost:number};
export type PurchaseOrder={
  id:string;
  owner_id?:string;
  orderNumber:string;
  supplierId?:string;
  supplierName:string;
  supplierPhone?:string;
  supplierEmail?:string;
  projectId?:string;
  projectName?:string;
  issueDate:string;
  expectedDate?:string;
  currency:string;
  status:PurchaseOrderStatus;
  items:PurchaseOrderLine[];
  subtotal:number;
  taxPercent:number;
  shipping:number;
  total:number;
  postedCost:number;
  deliveryLocation?:string;
  notes?:string;
  created_at?:string;
  updated_at?:string;
  sync_state?:'synced'|'pending'|'local';
};
export type MapPoint={lat:number;lng:number};
export type SiteMeasurementMode='distance'|'area';
export type SiteTakeoffLine={
  id:string;
  source:'map'|'calculator';
  tool:string;
  description:string;
  qty:number;
  unit:string;
  rate:number;
  note?:string;
};
export type CapturedLocation={
  point:MapPoint;
  accuracyM:number;
  capturedAt:string;
};
export type SiteMeasurement={
  id:string;
  owner_id?:string;
  name:string;
  projectId?:string;
  projectName?:string;
  customerId?:string;
  customerName?:string;
  mode:SiteMeasurementMode;
  tradeTool:string;
  points:MapPoint[];
  center:MapPoint;
  zoom:number;
  distanceM:number;
  perimeterM:number;
  areaM2:number;
  wastePercent:number;
  depthM:number;
  quantity:number;
  unit:string;
  description:string;
  unitRate:number;
  takeoffLines?:SiteTakeoffLine[];
  capturedLocation?:CapturedLocation;
  created_at:string;
  updated_at:string;
  sync_state?:'synced'|'pending'|'local';
};
export type TeamAvailability='Available'|'On job'|'Off duty'|'Leave';
export type TeamMember={id:string;name:string;role:string;phone:string;email:string;status:'Active'|'Inactive';hourlyRate?:number;crew?:string;skills?:string[];availability?:TeamAvailability};
export type WorkforceEntryStatus='active'|'break'|'completed';
export type WorkforceTimeEntry={
  id:string;
  owner_id?:string;
  member_id:string;
  member_name:string;
  project_id:string|null;
  project_name:string|null;
  clock_in:string;
  clock_out:string|null;
  break_started_at:string|null;
  break_minutes:number;
  hourly_rate:number;
  status:WorkforceEntryStatus;
  note:string|null;
  created_at?:string;
  updated_at?:string;
  sync_state?:'synced'|'pending'|'local';
};
export type LeadStatus='new'|'contacted'|'site_visit'|'quoted'|'won'|'lost';
export type LeadUrgency='normal'|'soon'|'urgent';
export type LeadSource='booking_page'|'manual'|'referral'|'phone'|'website';
export type BookingPage={
  id:string;
  owner_id?:string;
  slug:string;
  business_name:string;
  business_phone:string|null;
  business_email:string|null;
  service_area:string|null;
  welcome_message:string;
  services:string[];
  accent_color:string;
  active:boolean;
  created_at?:string;
  updated_at?:string;
};
export type ServiceLead={
  id:string;
  owner_id?:string;
  booking_page_id:string;
  source:LeadSource;
  customer_name:string;
  phone:string|null;
  email:string|null;
  service_type:string;
  site_address:string;
  preferred_date:string|null;
  preferred_time:string|null;
  budget_range:string|null;
  urgency:LeadUrgency;
  details:string|null;
  status:LeadStatus;
  follow_up_at:string|null;
  internal_notes:string|null;
  created_at:string;
  updated_at:string;
};
export type CommunicationChannel='whatsapp'|'email'|'phone'|'sms'|'meeting'|'note';
export type CommunicationDirection='outbound'|'inbound'|'internal';
export type CommunicationStatus='opened'|'sent'|'replied'|'no_answer'|'logged';
export type CommunicationRelatedType='general'|'estimate'|'invoice'|'project'|'lead';
export type ClientCommunication={
  id:string;
  owner_id?:string;
  customer_id:string;
  customer_name:string;
  channel:CommunicationChannel;
  direction:CommunicationDirection;
  subject:string|null;
  body:string;
  status:CommunicationStatus;
  occurred_at:string;
  follow_up_at:string|null;
  follow_up_completed_at:string|null;
  related_type:CommunicationRelatedType;
  related_id:string|null;
  created_at?:string;
  updated_at?:string;
  sync_state?:'synced'|'pending'|'local';
};
export type ClientMessageTemplate={
  id:string;
  owner_id?:string;
  name:string;
  channel:'whatsapp'|'email'|'sms';
  subject:string|null;
  body:string;
  active:boolean;
  created_at?:string;
  updated_at?:string;
  builtin?:boolean;
};

export type ServiceAssetStatus='Active'|'Needs service'|'Out of service'|'Retired';
export type ServiceAsset={
  id:string;owner_id?:string;customer_id:string;customer_name:string;name:string;type:string;
  manufacturer:string|null;model:string|null;serial_number:string|null;site_address:string|null;
  installed_on:string|null;warranty_until:string|null;status:ServiceAssetStatus;notes:string|null;
  created_at?:string;updated_at?:string;sync_state?:'synced'|'pending'|'local';
};
export type ServiceAgreementStatus='Draft'|'Active'|'Paused'|'Expired'|'Cancelled';
export type ServiceBillingCycle='Per visit'|'Monthly'|'Quarterly'|'Yearly';
export type ServiceAgreement={
  id:string;owner_id?:string;agreement_number:string;customer_id:string;customer_name:string;
  asset_ids:string[];plan_name:string;trade:string;status:ServiceAgreementStatus;start_date:string;
  end_date:string|null;next_visit_date:string|null;renewal_date:string|null;interval_days:number;
  billing_cycle:ServiceBillingCycle;price:number;auto_invoice:boolean;assigned_member_id:string|null;
  assigned_member_name:string|null;scope:string[];completed_visits:number;included_visits:number;
  notes:string|null;created_at?:string;updated_at?:string;sync_state?:'synced'|'pending'|'local';
};
export type ServiceVisitStatus='Scheduled'|'In progress'|'Completed'|'Skipped';
export type ServiceVisitChecklistItem={id:string;label:string;completed:boolean};
export type ServiceVisit={
  id:string;owner_id?:string;agreement_id:string;scheduled_for:string;status:ServiceVisitStatus;
  completed_at:string|null;technician_name:string|null;checklist:ServiceVisitChecklistItem[];
  notes:string|null;invoice_id:string|null;created_at?:string;updated_at?:string;
  sync_state?:'synced'|'pending'|'local';
};
