import { useEffect, useMemo, useState } from 'react';
import { Calculator, Check, ChevronLeft, Copy, FileText, Layers3, PackagePlus, Plus, Search, Sparkles, Trash2, UserPlus, UserRound, X } from 'lucide-react';
import type { Business, Customer, Estimate, InventoryItem, LineItem } from '../types';
import { getStored, setStored, uid } from '../lib/storage';

type BuilderItem=LineItem&{category:'Material'|'Labour'|'Service'|'Other'};
type Draft={customerId:string;project:string;date:string;validUntil:string;status:'Draft'|'Pending'|'Accepted';tax:number;discount:number;notes:string;items:BuilderItem[]};
const today=()=>new Date().toISOString().slice(0,10);
const addDays=(days:number)=>{const d=new Date();d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)};
const money=(v:number,c='GHS')=>new Intl.NumberFormat('en-GH',{style:'currency',currency:c}).format(v||0);
const blankItem=():BuilderItem=>({id:uid('ITM'),description:'',qty:1,unit:'pcs',rate:0,category:'Material'});
const isDemoCustomer=(c:Customer)=>c.id==='CUS-1001'&&c.name==='Ama Serwaa'&&c.email==='ama@example.com';
const cleanCustomers=(rows:Customer[])=>rows.filter(c=>!isDemoCustomer(c));
const templates=[
 {name:'8-camera CCTV installation',industry:'CCTV',items:[['Hikvision 2MP cameras',8,'pcs',480,'Material'],['8-channel NVR',1,'pcs',1500,'Material'],['2TB surveillance HDD',1,'pcs',850,'Material'],['Cat6 cable',180,'m',4.5,'Material'],['PVC conduit and accessories',1,'lot',420,'Material'],['Installation and configuration',1,'job',1600,'Labour']]},
 {name:'Starlink installation',industry:'Starlink',items:[['Starlink mounting pole',1,'pcs',450,'Material'],['Mounting accessories',1,'lot',250,'Material'],['Cable clips and weather sealing',1,'lot',120,'Material'],['Installation and alignment',1,'job',650,'Labour'],['Transport',1,'trip',180,'Service']]},
 {name:'Small solar backup system',industry:'Solar',items:[['Solar panels',4,'pcs',1250,'Material'],['Hybrid inverter',1,'pcs',4800,'Material'],['Lithium battery',1,'pcs',7200,'Material'],['Mounting and protection accessories',1,'lot',1650,'Material'],['Installation, wiring and commissioning',1,'job',2800,'Labour']]}
] as const;

export default function EstimateBuilder(){
 const[active,setActive]=useState(location.hash.includes('/estimates'));
 const[estimates,setEstimates]=useState<Estimate[]>(()=>getStored('q-estimates',[]));
 const[customers,setCustomers]=useState<Customer[]>(()=>cleanCustomers(getStored('q-customers',[])));
 const[inventory]=useState<InventoryItem[]>(()=>getStored('q-inventory',[]));
 const business=getStored<Business>('q-business',{name:'Quotiq',email:'',phone:'',address:'',taxId:'',bank:'',accountName:'',accountNumber:'',mobileMoney:'',estimatePrefix:'EST',invoicePrefix:'INV',currency:'GHS'});
 const[view,setView]=useState<'list'|'builder'>('list');
 const[editingId,setEditingId]=useState<string|null>(null);
 const[query,setQuery]=useState('');
 const[customerOpen,setCustomerOpen]=useState(false);
 const[customerForm,setCustomerForm]=useState({name:'',company:'',contactPerson:'',phone:'',email:'',siteAddress:'',billingAddress:''});
 const[message,setMessage]=useState('');
 const[draft,setDraft]=useState<Draft>({customerId:'',project:'',date:today(),validUntil:addDays(14),status:'Draft',tax:0,discount:0,notes:'',items:[blankItem()]});

 useEffect(()=>{const sync=()=>setActive(location.hash.includes('/estimates'));addEventListener('hashchange',sync);return()=>removeEventListener('hashchange',sync)},[]);
 useEffect(()=>{if(!active)return;document.body.classList.add('estimate-active');const cleaned=cleanCustomers(getStored<Customer[]>('q-customers',[]));setCustomers(cleaned);setStored('q-customers',cleaned);return()=>document.body.classList.remove('estimate-active')},[active]);
 const customer=customers.find(c=>c.id===draft.customerId);
 const subtotal=useMemo(()=>draft.items.reduce((s,i)=>s+(Number(i.qty)||0)*(Number(i.rate)||0),0),[draft.items]);
 const discountAmount=subtotal*(Number(draft.discount)||0)/100;
 const taxable=subtotal-discountAmount;
 const taxAmount=taxable*(Number(draft.tax)||0)/100;
 const total=taxable+taxAmount;
 const filtered=useMemo(()=>estimates.filter(e=>[e.id,e.customer,e.project,e.status].join(' ').toLowerCase().includes(query.toLowerCase())),[estimates,query]);

 const resetDraft=(customerId=customers[0]?.id||'')=>({customerId,project:'',date:today(),validUntil:addDays(14),status:'Draft' as const,tax:0,discount:0,notes:business.terms||'',items:[blankItem()]});
 const newEstimate=()=>{setMessage('');setEditingId(null);setDraft(resetDraft());setView('builder')};
 const editEstimate=(e:Estimate)=>{setMessage('');setEditingId(e.id);setDraft({customerId:e.customerId||'',project:e.project,date:e.date,validUntil:addDays(14),status:e.status,tax:e.tax||0,discount:e.discount||0,notes:'',items:(e.items||[]).map(i=>({...i,category:(i as BuilderItem).category||'Material'}))});setView('builder')};
 const updateItem=(id:string,key:keyof BuilderItem,value:any)=>setDraft(d=>({...d,items:d.items.map(i=>i.id===id?{...i,[key]:key==='qty'||key==='rate'?Number(value):value}:i)}));
 const removeItem=(id:string)=>setDraft(d=>({...d,items:d.items.length===1?d.items:d.items.filter(i=>i.id!==id)}));
 const addInventory=(item:InventoryItem)=>setDraft(d=>({...d,items:[...d.items,{id:uid('ITM'),description:item.name,qty:1,unit:item.unit||'pcs',rate:item.sellPrice||item.cost||0,category:'Material'}]}));
 const applyTemplate=(index:number)=>{const t=templates[index];setDraft(d=>({...d,project:t.name,items:t.items.map(([description,qty,unit,rate,category])=>({id:uid('ITM'),description:String(description),qty:Number(qty),unit:String(unit),rate:Number(rate),category:category as BuilderItem['category']}))}))};
 const save=(status:Draft['status']=draft.status)=>{setMessage('');if(!customer){setMessage('Select or add a customer before saving.');return}if(!draft.project.trim()){setMessage('Enter a project or job title.');return}const validItems=draft.items.filter(i=>i.description.trim());if(!validItems.length){setMessage('Add at least one item or service.');return}const prefix=business.estimatePrefix||'EST';const id=editingId||`${prefix}-${new Date().getFullYear()}-${String(estimates.length+1).padStart(4,'0')}`;const record:Estimate={id,customerId:customer.id,customer:customer.name,project:draft.project.trim(),amount:total,status,date:draft.date,items:validItems,tax:Number(draft.tax)||0,discount:Number(draft.discount)||0};const next=editingId?estimates.map(e=>e.id===editingId?record:e):[record,...estimates];setEstimates(next);setStored('q-estimates',next);window.dispatchEvent(new Event('quotiq-data'));setView('list')};
 const duplicate=(e:Estimate)=>{const copy={...e,id:`${business.estimatePrefix||'EST'}-${new Date().getFullYear()}-${String(estimates.length+1).padStart(4,'0')}`,status:'Draft' as const,date:today(),items:e.items.map(i=>({...i,id:uid('ITM')}))};const next=[copy,...estimates];setEstimates(next);setStored('q-estimates',next)};
 const remove=(id:string)=>{const next=estimates.filter(e=>e.id!==id);setEstimates(next);setStored('q-estimates',next)};
 const addCustomer=()=>{if(!customerForm.name.trim()||!customerForm.phone.trim()){setMessage('Customer name and phone number are required.');return}const newCustomer:Customer={id:uid('CUS'),name:customerForm.name.trim(),phone:customerForm.phone.trim(),email:customerForm.email.trim(),address:customerForm.siteAddress.trim(),company:customerForm.company.trim(),contactPerson:customerForm.contactPerson.trim(),siteAddress:customerForm.siteAddress.trim(),billingAddress:customerForm.billingAddress.trim(),status:'Active',tags:[],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};const next=[newCustomer,...customers];setCustomers(next);setStored('q-customers',next);setDraft(d=>({...d,customerId:newCustomer.id}));setCustomerForm({name:'',company:'',contactPerson:'',phone:'',email:'',siteAddress:'',billingAddress:''});setCustomerOpen(false);setMessage('Customer added and selected.')};
 if(!active)return null;

 return <div className="estimateMount">{view==='list'?<section className="estimatePage">
  <header className="estimateHero"><div><span>SMART ESTIMATING</span><h1>Estimates</h1><p>Create accurate contractor quotations with customers, items, tax and live totals.</p></div><button className="primary estimateCreateButton" onClick={newEstimate}><Plus size={18}/>Create estimate</button></header>
  <div className="estimateMetrics"><Metric label="Total estimates" value={String(estimates.length)}/><Metric label="Draft value" value={money(estimates.filter(e=>e.status==='Draft').reduce((s,e)=>s+e.amount,0),business.currency)}/><Metric label="Pending value" value={money(estimates.filter(e=>e.status==='Pending').reduce((s,e)=>s+e.amount,0),business.currency)}/><Metric label="Accepted" value={String(estimates.filter(e=>e.status==='Accepted').length)}/></div>
  <div className="estimateToolbar"><div><Search/><input placeholder="Search estimates, customers or projects…" value={query} onChange={e=>setQuery(e.target.value)}/></div><button className="primary compactCreate" onClick={newEstimate}><Plus/>New</button></div>
  <div className="estimateList">{filtered.map(e=><article className="estimateRow" key={e.id}><div className="estimateDocIcon"><FileText/></div><div className="estimateIdentity"><b>{e.id}</b><h3>{e.project}</h3><span>{e.customer} · {e.date}</span></div><div className="estimateValue"><strong>{money(e.amount,business.currency)}</strong><span className={`status ${e.status.toLowerCase()}`}>{e.status}</span></div><div className="estimateRowActions"><button onClick={()=>editEstimate(e)}>Edit</button><button title="Duplicate" onClick={()=>duplicate(e)}><Copy/></button><button title="Delete" onClick={()=>remove(e.id)}><Trash2/></button></div></article>)}{!filtered.length&&<div className="estimateEmpty"><Calculator/><h3>No estimates yet</h3><p>Add a customer and create your first estimate.</p><button className="primary" onClick={newEstimate}><Plus/>Create estimate</button></div>}</div>
 </section>:<section className="builderPage">
  <header className="builderTop"><button onClick={()=>setView('list')}><ChevronLeft/>Back</button><div><span>{editingId?'EDIT ESTIMATE':'NEW ESTIMATE'}</span><h1>{editingId||'Create an estimate'}</h1></div><div className="builderTopActions"><button onClick={()=>save('Draft')}>Save draft</button><button className="primary" onClick={()=>save('Pending')}><Check/>Save estimate</button></div></header>
  {message&&<div className="estimateNotice">{message}</div>}
  <div className="builderLayout"><main className="builderMain">
   <article className="builderCard"><div className="builderCardHead"><div><UserRound/><span>Customer & job</span></div><button className="addCustomerButton" onClick={()=>setCustomerOpen(true)}><UserPlus/>Add customer</button></div><div className="builderGrid"><label>Customer<select value={draft.customerId} onChange={e=>setDraft({...draft,customerId:e.target.value})}><option value="">Select a customer</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}{c.company?` — ${c.company}`:''}</option>)}</select></label><label>Project or job title<input value={draft.project} onChange={e=>setDraft({...draft,project:e.target.value})} placeholder="e.g. 8-camera CCTV installation"/></label><label>Estimate date<input type="date" value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></label><label>Valid until<input type="date" value={draft.validUntil} onChange={e=>setDraft({...draft,validUntil:e.target.value})}/></label></div>{!customers.length&&<div className="noCustomerPrompt"><UserPlus/><div><b>No customers yet</b><span>Add a customer to continue with this estimate.</span></div><button className="primary" onClick={()=>setCustomerOpen(true)}>Add customer</button></div>}{customer&&<div className="selectedCustomer"><b>{customer.name}</b><span>{customer.phone} · {customer.siteAddress||customer.address||'No site address'}</span></div>}</article>
   <article className="builderCard"><div className="builderCardHead"><div><Layers3/><span>Items & pricing</span></div><button onClick={()=>setDraft(d=>({...d,items:[...d.items,blankItem()]}))}><Plus/>Add line</button></div><div className="lineTable"><div className="lineHead"><span>Category</span><span>Description</span><span>Qty</span><span>Unit</span><span>Rate</span><span>Total</span><span/></div>{draft.items.map(i=><div className="lineItem" key={i.id}><select value={i.category} onChange={e=>updateItem(i.id,'category',e.target.value)}>{['Material','Labour','Service','Other'].map(x=><option key={x}>{x}</option>)}</select><input value={i.description} onChange={e=>updateItem(i.id,'description',e.target.value)} placeholder="Describe item or work"/><input type="number" min="0" value={i.qty} onChange={e=>updateItem(i.id,'qty',e.target.value)}/><input value={i.unit} onChange={e=>updateItem(i.id,'unit',e.target.value)}/><input type="number" min="0" value={i.rate} onChange={e=>updateItem(i.id,'rate',e.target.value)}/><strong>{money(i.qty*i.rate,business.currency)}</strong><button onClick={()=>removeItem(i.id)}><Trash2/></button></div>)}</div></article>
   <article className="builderCard"><div className="builderCardHead"><div><FileText/><span>Terms & notes</span></div></div><textarea rows={4} value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})} placeholder="Payment terms, warranty and exclusions…"/></article>
  </main><aside className="builderSide"><article className="builderCard"><div className="builderCardHead"><div><Sparkles/><span>Quick templates</span></div></div><div className="templateList">{templates.map((t,i)=><button key={t.name} onClick={()=>applyTemplate(i)}><i>{t.industry}</i><b>{t.name}</b><span>{t.items.length} items</span></button>)}</div></article><article className="builderCard"><div className="builderCardHead"><div><PackagePlus/><span>Price book</span></div></div><div className="priceBook">{inventory.slice(0,8).map(i=><button key={i.id} onClick={()=>addInventory(i)}><div><b>{i.name}</b><span>{i.quantity} {i.unit} available</span></div><strong>{money(i.sellPrice||i.cost,business.currency)}</strong><Plus/></button>)}{!inventory.length&&<p>Add inventory items to build a reusable price book.</p>}</div></article><article className="builderCard totalCard"><h3>Estimate summary</h3><label>Discount %<input type="number" min="0" max="100" value={draft.discount} onChange={e=>setDraft({...draft,discount:Number(e.target.value)})}/></label><label>Tax %<input type="number" min="0" max="100" value={draft.tax} onChange={e=>setDraft({...draft,tax:Number(e.target.value)})}/></label><div><span>Subtotal</span><b>{money(subtotal,business.currency)}</b></div><div><span>Discount</span><b>-{money(discountAmount,business.currency)}</b></div><div><span>Tax</span><b>{money(taxAmount,business.currency)}</b></div><div className="grandTotal"><span>Total</span><strong>{money(total,business.currency)}</strong></div><button className="primary" onClick={()=>save('Pending')}><Check/>Save estimate</button></article></aside></div>
 </section>}
 {customerOpen&&<div className="quickCustomerOverlay"><div className="quickCustomerModal"><div className="quickCustomerHead"><div><span>NEW CUSTOMER</span><h2>Add customer</h2></div><button onClick={()=>setCustomerOpen(false)}><X/></button></div><div className="quickCustomerGrid"><label>Customer or business name<input value={customerForm.name} onChange={e=>setCustomerForm({...customerForm,name:e.target.value})}/></label><label>Phone number<input type="tel" value={customerForm.phone} onChange={e=>setCustomerForm({...customerForm,phone:e.target.value})}/></label><label>Company (optional)<input value={customerForm.company} onChange={e=>setCustomerForm({...customerForm,company:e.target.value})}/></label><label>Contact person<input value={customerForm.contactPerson} onChange={e=>setCustomerForm({...customerForm,contactPerson:e.target.value})}/></label><label>Email<input type="email" value={customerForm.email} onChange={e=>setCustomerForm({...customerForm,email:e.target.value})}/></label><label>Site address<input value={customerForm.siteAddress} onChange={e=>setCustomerForm({...customerForm,siteAddress:e.target.value})}/></label><label>Billing address<input value={customerForm.billingAddress} onChange={e=>setCustomerForm({...customerForm,billingAddress:e.target.value})}/></label></div><div className="quickCustomerActions"><button onClick={()=>setCustomerOpen(false)}>Cancel</button><button className="primary" onClick={addCustomer}><UserPlus/>Add and select customer</button></div></div></div>}
 </div>
}
function Metric({label,value}:{label:string;value:string}){return <article><span>{label}</span><strong>{value}</strong></article>}
