import { useMemo, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { ArrowLeft, Calculator, FileText, Plus, Search, Trash2, UserRound, Users } from 'lucide-react';
import type { Business, Customer, Estimate, LineItem } from '../types';
import { getStored, setStored, uid } from '../lib/storage';

const today=()=>new Date().toISOString().slice(0,10);
const money=(value:number,currency='GHS')=>new Intl.NumberFormat('en-GH',{style:'currency',currency}).format(value||0);
const business=()=>getStored<Business>('q-business',{name:'Quotiq',email:'',phone:'',address:'',taxId:'',bank:'',accountName:'',accountNumber:'',mobileMoney:'',estimatePrefix:'EST',invoicePrefix:'INV',currency:'GHS'});

export function WorkspacePages(){
 const location=useLocation();
 if(location.pathname.startsWith('/customers')) return <CustomersPage/>;
 if(location.pathname.startsWith('/estimates')) return <EstimatesPage/>;
 return null;
}

function PageShell({children}:{children:React.ReactNode}){
 const navigate=useNavigate();
 return <div className="workspacePageShell"><header className="workspaceTopbar"><button onClick={()=>navigate('/')} className="workspaceBrand"><span>Q</span><b>Quotiq</b></button><nav><button onClick={()=>navigate('/customers')}>Customers</button><button onClick={()=>navigate('/estimates')}>Estimates</button><button onClick={()=>navigate('/')}>Dashboard</button></nav></header><main>{children}</main></div>
}

function CustomersPage(){
 const navigate=useNavigate(); const location=useLocation();
 const[customers,setCustomers]=useState<Customer[]>(()=>getStored('q-customers',[]));
 const[query,setQuery]=useState('');
 const isNew=location.pathname==='/customers/new';
 const filtered=useMemo(()=>customers.filter(c=>[c.name,c.phone,c.email,c.company,c.address,c.siteAddress].join(' ').toLowerCase().includes(query.toLowerCase())),[customers,query]);
 if(isNew)return <PageShell><CustomerForm onCancel={()=>navigate('/customers')} onSave={customer=>{const next=[customer,...customers];setCustomers(next);setStored('q-customers',next);navigate('/customers')}}/></PageShell>;
 return <PageShell><section className="workspacePage"><PageHeading eyebrow="CUSTOMER RELATIONSHIPS" title="Customers & CRM" description="Keep customer contacts, site information and job history connected." action={<button className="workspacePrimary" onClick={()=>navigate('/customers/new')}><Plus/>Add customer</button>}/><div className="workspaceMetrics"><Metric label="Customers" value={String(customers.length)}/><Metric label="Active customers" value={String(customers.filter(c=>c.status!=='Inactive').length)}/><Metric label="Outstanding" value={money(0,business().currency)}/><Metric label="Active projects" value="0"/></div><div className="workspaceSearch"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, phone, company or address…"/><span>{filtered.length} customers</span></div>{filtered.length?<div className="workspaceCards">{filtered.map(c=><article key={c.id} className="workspaceCustomerCard"><div className="workspaceAvatar">{c.name.slice(0,2).toUpperCase()}</div><div><h3>{c.name}</h3><p>{c.company||c.contactPerson||'Customer'}</p><span>{c.phone}{c.email?` · ${c.email}`:''}</span><small>{c.siteAddress||c.address||'No site address'}</small></div></article>)}</div>:<Empty icon={<Users/>} title="No customers found" text="Add your first customer to begin creating estimates." action={<button className="workspacePrimary" onClick={()=>navigate('/customers/new')}><Plus/>Add customer</button>}/>}</section></PageShell>
}

function CustomerForm({onCancel,onSave}:{onCancel:()=>void;onSave:(customer:Customer)=>void}){
 const[f,setF]=useState({name:'',company:'',contactPerson:'',phone:'',email:'',siteAddress:'',billingAddress:'',notes:''});
 const[error,setError]=useState('');
 const save=()=>{if(!f.name.trim()||!f.phone.trim()){setError('Customer name and phone number are required.');return}onSave({id:uid('CUS'),name:f.name.trim(),phone:f.phone.trim(),email:f.email.trim(),address:f.siteAddress.trim(),company:f.company.trim(),contactPerson:f.contactPerson.trim(),siteAddress:f.siteAddress.trim(),billingAddress:f.billingAddress.trim(),notes:f.notes.trim(),status:'Active',tags:[],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()})};
 return <section className="workspaceFormPage"><div className="workspaceFormHeader"><button onClick={onCancel}><ArrowLeft/>Back to customers</button><div><span>NEW CUSTOMER</span><h1>Add customer</h1><p>Create a customer record that can be used across estimates, invoices and projects.</p></div></div>{error&&<div className="workspaceError">{error}</div>}<div className="workspaceFormCard"><div className="workspaceFormGrid"><Field label="Customer or company name *"><input value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></Field><Field label="Company"><input value={f.company} onChange={e=>setF({...f,company:e.target.value})}/></Field><Field label="Contact person"><input value={f.contactPerson} onChange={e=>setF({...f,contactPerson:e.target.value})}/></Field><Field label="Phone number *"><input value={f.phone} onChange={e=>setF({...f,phone:e.target.value})}/></Field><Field label="Email"><input type="email" value={f.email} onChange={e=>setF({...f,email:e.target.value})}/></Field><Field label="Site address"><input value={f.siteAddress} onChange={e=>setF({...f,siteAddress:e.target.value})}/></Field><Field label="Billing address"><input value={f.billingAddress} onChange={e=>setF({...f,billingAddress:e.target.value})}/></Field><Field label="Notes" full><textarea rows={4} value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/></Field></div><div className="workspaceFormActions"><button onClick={onCancel}>Cancel</button><button className="workspacePrimary" onClick={save}>Save customer</button></div></div></section>
}

function EstimatesPage(){
 const navigate=useNavigate();const location=useLocation();
 const[estimates,setEstimates]=useState<Estimate[]>(()=>getStored('q-estimates',[]));
 const[query,setQuery]=useState('');
 const isNew=location.pathname==='/estimates/new';
 if(isNew)return <PageShell><EstimateForm estimates={estimates} onCancel={()=>navigate('/estimates')} onSave={record=>{const next=[record,...estimates];setEstimates(next);setStored('q-estimates',next);navigate('/estimates')}}/></PageShell>;
 const filtered=estimates.filter(e=>[e.id,e.customer,e.project,e.status].join(' ').toLowerCase().includes(query.toLowerCase()));
 return <PageShell><section className="workspacePage"><PageHeading eyebrow="SMART ESTIMATING" title="Estimates" description="Create accurate contractor quotations with customers, items, tax and live totals." action={<button className="workspacePrimary" onClick={()=>navigate('/estimates/new')}><Plus/>Create estimate</button>}/><div className="workspaceMetrics"><Metric label="Total estimates" value={String(estimates.length)}/><Metric label="Draft value" value={money(estimates.filter(e=>e.status==='Draft').reduce((s,e)=>s+e.amount,0),business().currency)}/><Metric label="Pending value" value={money(estimates.filter(e=>e.status==='Pending').reduce((s,e)=>s+e.amount,0),business().currency)}/><Metric label="Accepted" value={String(estimates.filter(e=>e.status==='Accepted').length)}/></div><div className="workspaceSearch"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search estimates, customers or projects…"/><span>{filtered.length} estimates</span></div>{filtered.length?<div className="workspaceEstimateList">{filtered.map(e=><article key={e.id}><FileText/><div><b>{e.id}</b><h3>{e.project}</h3><span>{e.customer} · {e.date}</span></div><strong>{money(e.amount,business().currency)}</strong><em>{e.status}</em></article>)}</div>:<Empty icon={<Calculator/>} title="No estimates yet" text="Add a customer and create your first estimate." action={<button className="workspacePrimary" onClick={()=>navigate('/estimates/new')}><Plus/>Create estimate</button>}/>}</section></PageShell>
}

function EstimateForm({estimates,onCancel,onSave}:{estimates:Estimate[];onCancel:()=>void;onSave:(estimate:Estimate)=>void}){
 const customers=getStored<Customer[]>('q-customers',[]);const biz=business();
 const[customerId,setCustomerId]=useState(customers[0]?.id||'');const[project,setProject]=useState('');const[date,setDate]=useState(today());const[tax,setTax]=useState(0);const[discount,setDiscount]=useState(0);const[items,setItems]=useState<LineItem[]>([{id:uid('ITM'),description:'',qty:1,unit:'pcs',rate:0}]);const[error,setError]=useState('');
 const subtotal=items.reduce((s,i)=>s+(Number(i.qty)||0)*(Number(i.rate)||0),0);const discountAmount=subtotal*discount/100;const taxable=subtotal-discountAmount;const total=taxable+taxable*tax/100;
 const update=(id:string,key:keyof LineItem,value:string|number)=>setItems(rows=>rows.map(i=>i.id===id?{...i,[key]:key==='qty'||key==='rate'?Number(value):value}:i));
 const save=()=>{const customer=customers.find(c=>c.id===customerId);const valid=items.filter(i=>i.description.trim());if(!customer){setError('Add or select a customer first.');return}if(!project.trim()){setError('Enter a project or job title.');return}if(!valid.length){setError('Add at least one item or service.');return}onSave({id:`${biz.estimatePrefix||'EST'}-${new Date().getFullYear()}-${String(estimates.length+1).padStart(4,'0')}`,customerId:customer.id,customer:customer.name,project:project.trim(),amount:total,status:'Draft',date,items:valid,tax,discount})};
 return <section className="workspaceFormPage estimateDedicated"><div className="workspaceFormHeader"><button onClick={onCancel}><ArrowLeft/>Back to estimates</button><div><span>NEW ESTIMATE</span><h1>Create estimate</h1><p>Build a professional quotation without leaving the Quotiq workspace.</p></div></div>{error&&<div className="workspaceError">{error}</div>}<div className="estimateDedicatedGrid"><main><div className="workspaceFormCard"><h2>Customer & job</h2>{customers.length?<div className="workspaceFormGrid"><Field label="Customer"><select value={customerId} onChange={e=>setCustomerId(e.target.value)}>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Project or job title"><input value={project} onChange={e=>setProject(e.target.value)}/></Field><Field label="Estimate date"><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></Field></div>:<div className="workspaceInlineEmpty"><UserRound/><div><b>No customers yet</b><span>Add a customer before creating an estimate.</span></div><button className="workspacePrimary" onClick={()=>location.hash='#/customers/new'}>Add customer</button></div>}</div><div className="workspaceFormCard"><div className="workspaceSectionHead"><h2>Items & pricing</h2><button onClick={()=>setItems([...items,{id:uid('ITM'),description:'',qty:1,unit:'pcs',rate:0}])}><Plus/>Add line</button></div><div className="workspaceLineItems">{items.map(item=><div key={item.id}><input className="description" placeholder="Description" value={item.description} onChange={e=>update(item.id,'description',e.target.value)}/><input type="number" min="0" value={item.qty} onChange={e=>update(item.id,'qty',e.target.value)}/><input value={item.unit} onChange={e=>update(item.id,'unit',e.target.value)}/><input type="number" min="0" value={item.rate} onChange={e=>update(item.id,'rate',e.target.value)}/><strong>{money(item.qty*item.rate,biz.currency)}</strong><button onClick={()=>setItems(items.length===1?items:items.filter(i=>i.id!==item.id))}><Trash2/></button></div>)}</div></div></main><aside><div className="workspaceFormCard workspaceSummary"><h2>Estimate summary</h2><Field label="Discount %"><input type="number" min="0" max="100" value={discount} onChange={e=>setDiscount(Number(e.target.value))}/></Field><Field label="Tax %"><input type="number" min="0" max="100" value={tax} onChange={e=>setTax(Number(e.target.value))}/></Field><div><span>Subtotal</span><b>{money(subtotal,biz.currency)}</b></div><div><span>Discount</span><b>-{money(discountAmount,biz.currency)}</b></div><div className="total"><span>Total</span><strong>{money(total,biz.currency)}</strong></div><button className="workspacePrimary" onClick={save}>Save estimate</button><button onClick={onCancel}>Cancel</button></div></aside></div></section>
}

function PageHeading({eyebrow,title,description,action}:{eyebrow:string;title:string;description:string;action:React.ReactNode}){return <header className="workspaceHeading"><div><span>{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{action}</header>}
function Metric({label,value}:{label:string;value:string}){return <article className="workspaceMetric"><span>{label}</span><strong>{value}</strong></article>}
function Empty({icon,title,text,action}:{icon:React.ReactNode;title:string;text:string;action:React.ReactNode}){return <div className="workspaceEmpty">{icon}<h3>{title}</h3><p>{text}</p>{action}</div>}
function Field({label,children,full=false}:{label:string;children:React.ReactNode;full?:boolean}){return <label className={full?'workspaceField full':'workspaceField'}><span>{label}</span>{children}</label>}
